name: Code Quality Check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Run Linter'
        run: npm run lint-check
      - name: 'Run Formatter'
        run: npm run format-check
